name: kics

on: [push, pull_request]



jobs:
  kics:
    name: kics-in
    runs-on: ubuntu-latest
    container:
      image: docker.io/checkmarx/kics:latest
    steps:
      - name: kics scan
      - uses: actions/checkout@v3
      - run: |
              echo "KICS_BLOCK_ON_HIGH: $KICS_BLOCK_ON_HIGH
              KICS_EXCLUDE_QUERIES: $KICS_EXCLUDE_QUERIES
              KICS_OUTPUT_NAME: $KICS_OUTPUT_NAME
              KICS_REPORT_FORMATS: $KICS_REPORT_FORMATS"
      - run: KICS_RESULT=$(kics scan --ci -p "$PWD" --exclude-queries "$KICS_EXCLUDE_QUERIES" --output-path "$PWD" --output-name "$KICS_OUTPUT_NAME" --report-formats "$KICS_REPORT_FORMATS" ) || true
      - run: export TOTAL_SEVERITY_COUNTER=`grep '"total_counter"':' ' kics-results.json | awk {'print $2'}`
      - run: export SEVERITY_COUNTER_HIGH=`grep '"HIGH"':' ' kics-results.json | awk {'print $2'} | sed 's/.$//'`
      - run: export SEVERITY_COUNTER_MEDIUM=`grep '"INFO"':' ' kics-results.json | awk {'print $2'} | sed 's/.$//'`
      - run: export SEVERITY_COUNTER_LOW=`grep '"LOW"':' ' kics-results.json | awk {'print $2'} | sed 's/.$//'`
      - run: export SEVERITY_COUNTER_INFO=`grep '"MEDIUM"':' ' kics-results.json | awk {'print $2'} | sed 's/.$//'`
      - run: |
            echo "TOTAL SEVERITY COUNTER: $TOTAL_SEVERITY_COUNTER
            SEVERITY COUNTER HIGH: $SEVERITY_COUNTER_HIGH
            SEVERITY COUNTER MEDIUM: $SEVERITY_COUNTER_MEDIUM
            SEVERITY COUNTER LOW: $SEVERITY_COUNTER_LOW
            SEVERITY COUNTER INFO: $SEVERITY_COUNTER_INFO"
      - run: if [ "$KICS_RESULT" -ge "50" ];then echo "Please fix all $SEVERITY_COUNTER_HIGH HIGH SEVERITY ISSUES" && exit 1; else exit 0;fi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kics reports
          path: |
                ./kics-results.html
                ./kics-results.pdf
                ./sonarqube-kics-results.json
