name: sonar

on:
  - pull_request
  - push

jobs:
  sonar:
    name: sonar
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:latest
    steps:
      - name: sonar
      - uses: actions/checkout@v3
      - run: sonar-scanner -Dsonar.qualitygate.wait=true
