name: Sonar

on:
  - pull_request
  - push

jobs:
  sonar:
    name: sonar
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: artifact
        uses: actions/download-artifact@v3
        with:
          name: kics-reports
      - name: scan
        run: sonar-scanner -Dsonar.qualitygate.wait=true
